---
- name: create vm 
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
      - name: create VM
        vmware_guest:
          hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"
          username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
          password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: "{{ vcenter_datacenter }}"
          name: "{{ vm_name }}"
          template: "{{ template_name }}"
          folder: "{{ vcenter_destination_folder }}"
          state: "{{ vm_state }}"
#          guest_id: "{{ vm_guestid }}"
          cluster: "{{ vcenter_cluster }}"
          wait_for_ip_address: True
          disk:
            - size_gb: "{{ vm_disk_gb }}"
              type: "{{ vm_disk_type }}"
              datastore: "{{ vm_disk_datastore }}"
          hardware:
            memory_mb: "{{ vm_hw_ram_mb }}"
            num_cpus: "{{ vm_hw_cpu_n }}"
            scsi: "{{ vm_hw_scsi }}"
